export const allPocket = [
  {
    balanceTarget: 35000000,
    color: "bg-pink-wondr",
    friends: ["AMIRA FERIAL", "IVANKA LARASATI KUSUMADEWI PUTRI SYALALALA"],
    goalTitle: "Wisata bersama",
    icon: "Airplane",
    id: 1,
    name: "Pergi ke Swiss",
    subject: "Personal",
    targetDuration: {
      endDate: "2026-01-30T23:59:59.999Z",
      startDate: "2025-06-17T17:00:00.000Z",
    },
    type: "Saving",
  },
  {
    balanceTarget: null,
    color: "bg-orange-wondr",
    friends: [],
    goalTitle: null,
    icon: "Pocket",
    id: 2,
    name: "Uang Bulanan",
    subject: "Personal",
    targetDuration: { endDate: undefined, startDate: undefined },
    type: "Spending",
  },
  {
    balanceTarget: 10000000000,
    color: "bg-lime-wondr",
    friends: [
      "FARREL BRIAN RAFI",
      "DAFFA HAFIIZH PERMADI",
      "AMIRA FERIAL",
      "IVANKA LARASATI KUSUMADEWI PUTRI SYALALALA",
      "MARTUAH FERNANDO SIBARANI",
      "NAUFAL MU'AFI",
      "SHIDQI FADHLURRAHMAN YUSRI",
    ],
    goalTitle: "Bisnis Otomotif",
    icon: "Pocket",
    id: 3,
    name: "OKJEK",
    subject: "Personal",
    targetDuration: {
      endDate: "2025-10-30T23:59:59.999Z",
      startDate: "2025-06-17T17:00:00.000Z",
    },
    type: "Business Fund",
  },
  {
    balanceTarget: 400000000,
    color: "bg-purple-wondr",
    friends: [
      "DAFFA HAFIIZH PERMADI",
      "IVANKA LARASATI KUSUMADEWI PUTRI SYALALALA",
    ],
    goalTitle: "Pernikahan",
    icon: "Diamond",
    id: 4,
    name: "Get Married by 2027",
    subject: "Personal",
    targetDuration: {
      endDate: "2025-11-29T23:59:59.999Z",
      startDate: "2025-06-17T17:00:00.000Z",
    },
    type: "Saving",
  },
];
